apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort        # perfecto para probar en Minikube
  selector:
    app: grafana
  ports:
    - port: 80          # puerto dentro del cluster
      targetPort: 3000  # puerto del contenedor
      nodePort: 32000   # fijo; omítelo para que se asigne aleatorio
